- hosts: app
  become: yes
  tasks:
    - name: Add an apt signing key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      block:
        - apt:
            update_cache: no
        - apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu hirsute stable
            state: present
            update_cache: no

    - name: Install Docker
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - docker-ce
        - docker-ce-cli 
        - containerd.io
        
    - name: Install docker-compose
      remote_user: ale
      get_url: 
        url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
    
    - name: Copy todo application
      copy:
        src: app
        dest: /home/ale
    
    - name: Run docker compose
      shell: "cd /home/ale/app && docker-compose run --detach -p 3000:{{ port }} app sh -c 'yarn install && yarn run dev'"
